### ISSUE TITLE
Add Image for each pipeline status - Green, Yellow, Red

### ISSUE THREAD

**Issue by kambale** [build-canaries/nevergreen#104]
It will be nice to have an option to actually add image for every status other than green.

**Comment by GentlemanHal** [comment]
@kambale thanks for opening this issue!

At what point would you expect these other images to be shown?

Also there is no green, just success! :wink:

**Comment by kambale** [comment]
Hi @GentlemanHal. What I mean is that when there is a success on the pipeline, currently the system allows you to have an image for success. I was asking if it is possible that whenever the code is being build (yellow), we can configure that stage to display an image or leave the default yellow page with name of the pipeline and that when the build is red, we also can set an image or leave the default red page with the branch title.

In terms of what should happen if we have multiple pipeline, the messages should have the name of the pipeline and the default image for the stage in the build.

**Comment by GentlemanHal** [comment]
So if I understand correctly, you'd like to add one image for the other prognoses (clean-building, broken-building and broken) that gets used instead of the colours.

I can see several issues with implementing this feature:

* It would be possible for someone to pick an image that makes the text difficult to read (which defeats the point of a team build monitor).
* It would be impossible to get an image that fitted correctly as the ratio depends on the number of projects currently doing something 'interesting'.
* Stretching images would look bad so the ratio would have to be maintained.
    * Do we leave black space around the image?
    * Do we scale along the smallest edge, cropping or zooming the image? 

Ultimately I think this just wouldn't look very nice for most situations (i.e. multiple projects being monitored), so unfortunately I'm inclined to mark this as "won't fix".

@joejag @cowley05 Thoughts?

**Comment by kambale** [comment]
Thanks @GentlemanHal for looking into this. May be I am not explaining it correctly. Currently the website is already displaying an image for Success. All I am asking is that rather having a message for the different prognoses, can you let users add an image instead of having a text and color displayed.

Totally understand if this is not possible. Nonetheless, thank you for looking into this.

**Comment by GentlemanHal** [comment]
Currently success means nothing "interesting" (you can check the source to see how we define interesting) is happening, this is because Nevergreen makes a point of **not** displaying projects that have passed the build process successfully (hence the name compared to other build monitors!).

So if we didn't allow a custom success message or image to be set the screen would just be blank. This was how the first version actually worked and the team thought the monitor was turned off!

> All I am asking is that rather having a message for the different prognoses, can you let users add an image instead of having a text and color displayed.

The text being displayed when a project is doing something interesting is the name of the project, this is very important information. So the 'message' can not be replaced with just an image as it would be impossible to know which project was in which state. It would be possible to replace the coloured background with an image instead, but that would bring all the issue mentioned in my first reply.

It case I'm still misunderstanding what you would like, could you explain how you'd expect the following view to look after your proposed changes?

![example](https://raw.githubusercontent.com/build-canaries/nevergreen/master/doc/screenshot.png)

**Comment by GentlemanHal** [comment]
Am marking this as won't fix and closing. Given my current understanding I feel this would detract from the primary purpose of being an information radiator, making it harder to figure out which projects are in which states.
