### ISSUE TITLE
Unable to fetch projects from Go 15.2.0

### ISSUE THREAD

**Issue by portovep** [build-canaries/nevergreen#105]
Since we updated to v.0.7.0 we are not able to add the configuration for our CI. 

Steps to reproduce:
+ When we click on "ADD" we don't get any feedback from the app.
+ If we check the logs from the app using docker (docker logs <container_id>) we get INFO log entries with a POST request to the "/api/encrypt" endpoint.

We have reverted to v0.6.0 for now.

Versions:
Go: 15.2.0(2248-c1f90a6aa3192a)
Nevergreen: 0.7.0

**Comment by GentlemanHal** [comment]
@portovep thanks for raising this issue, sorry it took so long to reply.

I tried installing that version of Go locally and set up some auth. Both my local build and nevergreen.io seemed to be working correctly, also the cctray.xml being generated by that version of Go seems to be correct. So I don't think it has anything to do with Go specifically.

I assume you are installing locally using the Docker image? I suspect it might be something specific to either installing from Docker (we aren't dog fooding that yet) or your system.

The client side code has changed quite a bit because of #101 so it's probably worth waiting until we release v0.8.0 and trying again to see if the issue persists.

Sorry I can't be more help at this time.

**Comment by portovep** [comment]
Thanks @GentlemanHal for taking time to look into this. I don't have access to the build monitor of the project anymore but I encourage @chambois and @Binsabbar to keep and eye on this and try version v0.8.0 once it is out.

Thanks again.

**Comment by GentlemanHal** [comment]
v0.8.0 has been release, so if @chambois and/or @Binsabbar are able to try testing this again for us we'd really appreciate it.

**Comment by GentlemanHal** [comment]
v0.9.0 has now been released, and since no one has responded I'm going to assume this was some environment specific issue.

If anyone is able to test with v0.9.0 and provide us with more info I'll open the issue again.
