### ISSUE TITLE
Pipelines with "similar" names are only shown once

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#130]
So this is a little strange of a use case but here is an example, if I have a pipeline called: "stes-pipeline" and another pipeline called "StesPipeline", then this is displayed as "stes pipeline" but only one of them.

This is the same when you use any variant of what would be the same pipeline name after it is sentencised.

The project i'm on has some pipelines named like this and unfortunately we cant easily change/get around this as we screwed up a long time ago ;) @joejag  and @GentlemanHal you probably know the project im talking about. It is an edge case and usually you wouldn't want to have 2 pipelines with similar names like that but it is a possibility.

**Comment by GentlemanHal** [comment]
Renaming projects in most CI servers is pretty tedious and error prone but there shouldn't be a reason it can't be done, unless I'm missing something? In GO the easiest way is to just edit the XML directly...

Having said that, there might be a fairly easy fix for this by generating the project id from the url instead of the name. You'd still have the problem of not know which one of the projects was actually broken, so this does feel like a more fundamental problem with your naming scheme!

**Comment by jimmythompson** [comment]
Is this two projects within the same tray, or two projects in different trays? I've noticed that adding the same tray twice means that not only does it only show one of them, but it doesn't size the boxes correctly. Is this the same thing?

![ng](https://cloud.githubusercontent.com/assets/653864/13093607/2e329dec-d4fe-11e5-867a-134fa348824a.gif)

**Comment by GentlemanHal** [comment]
@jimmythompson It's a similar issue, we generate project ids from the name and we use those as the React key. So the reason the boxes aren't size correctly is because we are calculating the math based on all the interesting projects from both trays, but when we add them to the virtual DOM React thinks they are already added so doesn't add them again.

If you look at your console you'll probably see a React warning (you'll probably need to be running locally as I think the checks get removed for production)

**Comment by GentlemanHal** [comment]
Have created #131 to disallow the same tray being added multiple times, thanks @jimmythompson
