### ISSUE TITLE
Migrate away from Snap CI

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#161]
We will soon need to move away from Snap CI. 

Circle CI has been mentioned as the only option so far.

If anyone has more details of other options it would be great to hear but otherwise we could go migrate directly to Circle CI.

https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/

**Comment by GentlemanHal** [comment]
CircleCI is now handling everything but deployment to production.

I've added what I believe are the correct commands to the circle.yml file, but they are currently commented out. This is because there is not real way of testing them before pushing to CircleCI and I don't want to accidentally deploy to production.

Once we are ready to do the next deployment we can uncomment those lines and tweak as required until we get a successful deployment. Once that is done we can close this issue.
