### ISSUE TITLE
https://nevergreen.io/ is down

### ISSUE THREAD

**Issue by rahulmr** [build-canaries/nevergreen#194]
https://nevergreen.io/ is down and giving below error.

**503 Service Unavailable

No server is available to handle this request.**

**Comment by GentlemanHal** [comment]
Hi @rahulmr 

Thanks for reporting this, I've restarted the process now so it is back up. Sorry for any problems this may have caused.

We have Pingdom set up to check and alert us via email, but for some reason I don't have any emails 😕 (whilst writing this response I got an email telling me it was back up... 😖)

As much as I'd love teams to be able to get up and running quickly using nevergreen.io, in reality this hasn't turned out to be the case. Most teams I know using Nevergreen are actually hosting their own version (mostly due to firewall issues).

This has resulted in the team neglecting the maintenance of nevergreen.io and I can't in good conscience recommend using it right now, it's just too flakey at the moment 😞. For now if you are able I'd suggest hosting your own version internally.

If you'd like to keep track of our efforts to make nevergreen.io more reliable you can follow this issue in the infra project:

https://github.com/build-canaries/nevergreen-infra/issues/9

It's a little light on concrete actions, so any ideas are welcome.

**Comment by rahulmr** [comment]
Thanks for doing the needful. And yes this project is great. I have created a Docker container for our purpose when the site was down and it helped us. I think keeping docker image updated can help in this regard. I am particularly facing an issue in which I see that the font size is very small when the number of GOCD pipelines failing is more.  
I will try to raise an issue for the same, seems like css needs some updates. 
We have around 70+ GoCD pipelines failing which we wanted to reduced ASAP.
When we open the monitor link we see very tiny font. When we try to zoom-in chrome browser the size again decreases instead of increasing and increases when we zoom-out. :( 
:)
