### ISSUE TITLE
Hide password field when entering password in nevergreen tracking page

### ISSUE THREAD

**Issue by cisum-la** [build-canaries/nevergreen#219]
For bug reports please fill in as many of the following details as possible:

1. how are you running - downloaded jar
2. version - v1.0.0+588.d7c07c1 Lapis Lazuli
3. Chrome- Version 65.0.3325.181 (Official Build) (64-bit)
4. CI server -  `GoCD` and Jenkins
5. steps to reproduce?
<img width="809" alt="screen shot 2018-04-09 at 5 10 35 pm" src="https://user-images.githubusercontent.com/9635484/38529588-861351d4-3c1a-11e8-9102-a1bba5887a64.png">

 - Start nevergreen server
-  Click on Tracking button 
- Enter password, note that it is not hidden/masked but shows up in plain text.

**Comment by GentlemanHal** [comment]
Hi @cisum-la, thanks for submitting this bug report.

This has been fixed by #88 which is in master but not part of an official release yet. If you need the functionality now, you can compile your own jar from source. The wiki has a [contributing page](https://github.com/build-canaries/nevergreen/wiki/contributing) with more info about building and running from source.
