### ISSUE TITLE
Request: Info for Concourse

### ISSUE THREAD

**Issue by BlacktoBlue** [build-canaries/nevergreen#228]
I am looking to create a standalone API to convert Concourse pipelines into a CCTRAY.XML format.

Can someone please provide me with the following information?
1. A CCTray.xml spec? maybe a go cctray.xml example?
2. Does nevergreen send the username and password in the request e.g. username:password@server.com/cctray.xml?

**Comment by GentlemanHal** [comment]
Hi @BlacktoBlue 

The closest thing to a spec I've been able to find is at https://github.com/robertmaldon/cc_dashboard#summary

Nevergreen also has some [example CCTray XML files](https://github.com/build-canaries/nevergreen/tree/master/ci_stub_server) that we use for testing.

Currently Nevergreen only supports [basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication), and if you use the username/password input boxes on the UI the credentials get sent using a HTTP header. You could manually enter the username and password into the URL field if you wanted to send them URL encoded instead (although this isn't recommended and is actually deprecated).

> Use of the format "user:password" in the userinfo field is deprecated.
> https://www.ietf.org/rfc/rfc3986.txt

**Comment by GentlemanHal** [comment]
I'm going to close this issue for now, if you have any more questions just comment here (assuming notifications are still sent, if not, reopen and then comment) or [sign up to our Slack workspace](https://join.slack.com/t/nevergreen/shared_invite/enQtMzc4MDg5MTE2MDE2LWJjYjdiNDM4Y2U1YjBjZTdkZjFhZGQyOTM5ODQ2MzEwZDY4YjNiZDFmOTFlMGUwOWEyMjczNmUzNTlkZDk4ZmQ).

If you decide to open source what ever you build, could you please comment on issue #183 so that others can use it!
