### ISSUE TITLE
You can still change tabs while project list is loading

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#50]
The loading spinner overlay should block the entire page until the call returns

**Comment by cowley05** [comment]
not sure this is actually a bug? Ive tried to cause problems when this happens but i couldnt break it and since the monitor page redirects you back if there are no projects it doesnt break that either, even if it fails to fetch you just see the error failed to fetch on monitor. I dont think its a problem that you can go edit the success or timing whilst its fetching.

thoughts???

**Comment by GentlemanHal** [comment]
My internet at home can be very slow so that gave me enough time to be able to mess with the page. 

I'd imagine If you are on a slow connection fetching a large xml you could replicate.

**Comment by GentlemanHal** [comment]
Since the React refactor the loading of projects is tied nicer into the mounting of sections into the DOM.

I don't think this bug is relevant anymore, so I'm going to close it. Feel free to reopen if you disagree.
