### ISSUE TITLE
Switch to Jest for JS testing?

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#78]
Should we try switching to [Jest](https://facebook.github.io/jest/) for testing the JS?

It was also created by Facebook and is what they use to test React itself.

Thoughts?

**Comment by cowley05** [comment]
Do you know what the benefits are?

**Comment by GentlemanHal** [comment]
Mostly all the stuff listed on the page I linked, it just looks like it might be simpler than using Karma.

Since we already have Karma set up it might not be worth switching now.

**Comment by joejag** [comment]
Wow, that sounds pretty awesome. Twice I tried changing the test framework to Chao + Mocka. Karma is really for DOMy JS apps whereas we are a nodey JS app.

It's using Jasmine too, so we don't need to change our expect() code.

+1: but it's a pain to do, as you really want to change all the tests at once, rather than incrementally

**Comment by GentlemanHal** [comment]
@joejag @cowley05 Have switched all the existing tests and added a new view test. Everything seems to be working fine locally and on CI, its probably a good idea to see if you guys can still build locally OK.

**Comment by cowley05** [comment]
All looks good to me im happy to close.
