### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#81]
To make navigating easier.

**Comment by GentlemanHal** [comment]
We now have some keyboard shortcuts :smile: 

Some feedback on whether they make sense or not would be good (@joejag @cowley05) before we close this issue.

**Comment by joejag** [comment]
Keyboard shortcuts shouldn't be the highest help option.  I reckon between "success" and "additional links"

LOVE the 1,2,3,4,5.

The tracking page index based select all is a bit hard to figure out. That in general makes me think we should add hints like parens with the hotkey.

**Comment by GentlemanHal** [comment]
I agree the index stuff is very clunky, can you think of a better set of hotkeys or do you think we just need hints?

Where would you want the hotkey hints to be shown, as part of the elements text, as a tooltip style hover? Perhaps we could use a modifier key (ctrl, cmd) that once pressed shows the hints?

**Comment by joejag** [comment]
I like the idea of the modifier key decorating the buttons. Is that possible to do? I suppose so. 

Showing them all the time would clutter the UI up a bit. But it works for the index-tray actions.

We could improve the keyboard navigation experience by using highlighting on buttons. You cannot tell when they are selected at present.

**Comment by barisbalic** [comment]
I like the navigation keys, the bindings for manipulating messages etc seem a bit over complicated, I can understand why but I'd just consider if they are worth keeping at all.

Modifier key to expose shortcuts is cool idea.

**Comment by cowley05** [comment]
Love this! I do like the idea of the modifier shortcut display thing, i'm imagining something like pressing the 'f' key in vimium? I think for now though whats there would suffice?

The index things are complicated but i think they would become easier if we did the highlight on modifier key.

I think it would be nice if when you press the help screen shortcut 'h' it took you to the help screen as it does now but if you press '?' it took you there and scrolled down to the shortcuts section. Just because ? is kind of the standard now for the list of shortcuts.

I think with a tidy up of the table it would be good to go for this release and do the other enhancements later on.

**Comment by barisbalic** [comment]
@GentlemanHal vimium is exactly the thing I was trying to remember when we talked about this the other day.

**Comment by GentlemanHal** [comment]
> The index things are complicated but i think they would become easier if we did the highlight on modifier key.

Am playing around with some ideas now. Will probably be something simple like replace the button text with the shortcut key as getting things to hover nicely and too much css for my brain.

> Also the display shortcut 'd' is a little dodgy sometimes for instance if you press 'e' then wait a second press 'd' it doesn't work and you have to press again.

That's because I've also assigned 'd' as part of a chain to remove success messages, I will fix that.

**Comment by GentlemanHal** [comment]
Been playing around with highlighting shortcuts, pressing `?` at any point causes tooltips to appear above the buttons with hotkeys which automatically disappear after 2 seconds.

![nevergreen-shortcuts](https://cloud.githubusercontent.com/assets/415521/13125418/5fec3b94-d5bd-11e5-8a29-8f1c988c8aee.gif)

Thoughts?

**Comment by barisbalic** [comment]
My thoughts are that your gif should be 8 seconds of the tooltips showing, instead of 10 seconds of jack shit followed by 1.5 seconds of the tooltips showing.

Aside from that, I like it but the colour is a little jarring.

**Comment by barisbalic** [comment]
Man I'm serious, I'd take a fucking JPEG over that GIF right now.  I had to get out of bed to tell you this.

**Comment by joejag** [comment]
I'm liking the direction this is taking.

We will need to give some UI love to the tooltips.

**Comment by GentlemanHal** [comment]
<img width="1321" alt="screen shot 2016-02-19 at 21 15 52" src="https://cloud.githubusercontent.com/assets/415521/13191550/75acb526-d75c-11e5-89ae-6f9fe95e445c.png">

**Comment by GentlemanHal** [comment]
@joejag @cowley05 Have committed some updates, if you could check again and let me know what you think

**Comment by cowley05** [comment]
@GentlemanHal had a look through it just, looks good to me mate.

Tested all of the shortcuts from various locations (not sure i got all permutations obviously) but it looks good to go for me.

**Comment by joejag** [comment]
+1 looks good. I like the help bit. 

It's a shame we don't have outlines around the project names due to https://github.com/build-canaries/nevergreen/blob/master/src/scss/modules/_checkboxes.scss#L75

However, the way those checkboxes are working makes it difficult to add an outline (the boxes aren't grown as you'd expect, so it's off centre when you apply an outline).

**Comment by GentlemanHal** [comment]
@joejag yeah, I tried adding a focus but couldn't figure out how to make it look good.
